### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by PxnTxgoN** [Hancapo/VichoTools#16]
When exporting as a YTD, an error occurs and the file is not created, I have several drawable models in the meshes

Yes, everything is as up-to-date as possible

![image](https://github.com/Hancapo/VichoTools/assets/68269111/a0e0d9f4-91c7-4c7d-bf87-a655a58496cd)
![image](https://github.com/Hancapo/VichoTools/assets/68269111/17845939-90f6-4c2e-bbc1-19d5c5125b39)

**Comment by Hancapo** [comment]
One of your meshes' materials have an empty image texture node.

**Comment by PxnTxgoN** [comment]
Oh thank you, yes I found it and it worked immediately. : / #100%Brain
