### ISSUE TITLE
Blender is freezing when using YTD Export

### ISSUE THREAD

**Issue by Yam-Ka** [Hancapo/VichoTools#2]
When clicking Export YTD, Blender is freezing :

![image](https://user-images.githubusercontent.com/114988545/223956653-f486fc55-1a23-4ed8-a87c-0dbaaab3c850.png)

It's reworking normally when i stop Folder2YTD task in the example above. Process is creating texture folder and files like folder export (which is working perfectly) but never create the .ytd file.

I have the latest version of Vichotools and the latest release of Folder2YTD (0.4.0.3). Blender Version is 3.3.

**Comment by Hancapo** [comment]
Sorry for the last response, it should be working now with the

**Comment by Hancapo** [comment]
You must Run Blender as administrator to avoid most freezes.
